{{- if .Values.certificate.enabled -}}
# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# Source: iag5/templates/certificate.yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "iag5.fullname" . }}-tls
  labels:
    {{- include "iag5.labels" . | nindent 4 }}
spec:
  secretName: {{ include "iag5.fullname" . }}-tls-secret
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: {{ .Values.certificate.issuerRef.kind }}
  commonName: {{ .Values.certificate.hostname }}
  dnsNames:
    - {{ .Values.certificate.hostname }}
  renewBefore: {{ .Values.certificate.renewBefore }}
  duration: {{ .Values.certificate.duration }}
{{- end -}}