{{- if .Values.ingress.enabled -}}
# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# Source: iag5/templates/ingress-class.yaml
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingress.className }}
  labels:
    {{- include "iag5.labels" . | nindent 4 }}
spec:
  controller: k8s.io/ingress-nginx
{{- end }}