---
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingress.className }}
  labels:
    {{- include "iag5.labels" . | nindent 4 }}
spec:
  controller: k8s.io/ingress-nginx
{{- end }}