# Copyright (c) 2025, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# Source: iag5/templates/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "iag5.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: iag5-service-port
  selector:
    {{- include "iag5.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
