# Default values for iag5.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# These are used by the NOTES.txt template
hostname: iag5.pet-sbx.itential.io
port: 50051

# image The Itential image to use, its version, and its location
image:
  repository: "itential.jfrog.io/gateway5-image/gateway5"
  name: "itential.jfrog.io/gateway5-image/gateway5"
  tag: "5.1.0-dev1-amd64"
  pullPolicy: "IfNotPresent"

# imagePullSecrets The secrets object used to pull the image from the repo
imagePullSecrets:
  - name: "jfrogcred"

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

# service The Kubernetes service object for this application
service:
  # type The service type
  type: "LoadBalancer"
  # name The name of this Kubernetes service object
  name: "iag5-service"
  # port The port that this service object is listening on
  port: 50051
  # targetPort The application port that this service object will send requests to
  targetPort: 50051
  # annotations on the service object, passed through as is
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    external-dns.alpha.kubernetes.io/hostname: iag5.pet-sbx.itential.io
    external-dns.alpha.kubernetes.io/ttl: "60"

# ingress The Kubernetes ingress object for this application.
ingress:
  # enabled The ingress object can be disabled and will not be created with this set to false
  enabled: false
  # name The name of this Kubernetes ingress object
  name: "iag5-ingress"
  # className The ingress controller class name
  className: "nginx"
  hostname: "iag5.pet-sbx.itential.io"
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/hostname: iag5.pet-sbx.itential.io
    external-dns.alpha.kubernetes.io/ttl: "60"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls: []

issuer:
  enabled: true
  name: iag5-ca-issuer
  caSecretName: iag5-ca

certificate:
  enabled: true
  issuerRef:
    name: iag5-ca-issuer
    kind: Issuer
  renewBefore: 48h
  duration: 2160h
  hostname: iag5.pet-sbx.itential.io

resources: {}

livenessProbe:
  enabled: true
  settings:
    exec:
      command:
        - /bin/sh
        - -c
        - pgrep iagctl > /dev/null
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

readinessProbe:
  enabled: true
  settings:
    exec:
      command:
        - /bin/sh
        - -c
        - pgrep iagctl > /dev/null
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3

autoscaling:
  enabled: false

runnerSettings:
  replicaCount: 3
  env:
    GATEWAY_RUNNER_CERTIFICATE_FILE: /etc/ssl/gateway/tls.crt
    GATEWAY_RUNNER_PRIVATE_KEY_FILE: /etc/ssl/gateway/tls.key
    GATEWAY_RUNNER_LISTEN_ADDRESS: "0.0.0.0"
    GATEWAY_RUNNER_USE_TLS: false

serverSettings:
  replicaCount: 1
  env:
    GATEWAY_SERVER_DISTRIBUTED_EXECUTION: true
    GATEWAY_SERVER_CERTIFICATE_FILE: "/etc/ssl/gateway/tls.crt"
    GATEWAY_SERVER_PRIVATE_KEY_FILE: "/etc/ssl/gateway/tls.key"
    GATEWAY_SERVER_LISTEN_ADDRESS: "0.0.0.0"
    GATEWAY_SERVER_USE_TLS: false

applicationSettings:
  etcdTlsSecretName: etcd-tls-secret
  env:
    GATEWAY_APPLICATION_CA_CERTIFICATE_FILE: /etc/ssl/gateway/ca.crt
    GATEWAY_LOG_LEVEL: INFO
    GATEWAY_COMMANDER_ENABLED: false
    GATEWAY_STORE_BACKEND: etcd
    GATEWAY_STORE_ETCD_HOSTS: "etcd.default.svc.cluster.local:2379"
    GATEWAY_STORE_ETCD_USE_TLS: false
    GATEWAY_STORE_ETCD_CA_CERTIFICATE_FILE: /etc/ssl/etcd/ca.crt
    GATEWAY_STORE_ETCD_CERTIFICATE_FILE: /etc/ssl/etcd/tls-client.crt
    GATEWAY_STORE_ETCD_CLIENT_CERT_AUTH: true
    GATEWAY_STORE_ETCD_PRIVATE_KEY_FILE: /etc/ssl/etcd/tls-client.key

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
